services:
  redis:
    image: redis:8.0

  proxy:
    image: ghcr.io/mbroton/playwright-distributed/proxy:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      # Maximum number of concurrent browser sessions allowed
      - MAX_CONCURRENT_SESSIONS=5
      # Maximum number of sessions a worker will handle before it is recycled. The proxy tracks this for each worker.
      - MAX_LIFETIME_SESSIONS=50
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    image: ghcr.io/mbroton/playwright-distributed/worker:latest
    environment:
      - REDIS_URL=redis://redis:6379
      # Port for the worker to listen on for browser connections
      - PORT=3131
      # Hostname for the worker, registered in Redis. Must be resolvable by the proxy.
      - PRIVATE_HOSTNAME=worker
      - LOG_LEVEL=info
      - LOG_FORMAT=text
    depends_on:
      - redis
    restart: unless-stopped
